apiVersion: v1
data:
  app-room.toml: |
    [global]
    # data center id
    dc = "dc1"

    [log]
    level = "info"
    # level = "debug"

    [nats]
    url = "nats://nats:4222"

    [redis]
    addrs = ["redis:6379"]
    password = ""
    db = 0
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-room-config
