[log]
level = "info"
# level = "debug"

[postgres]
addr = "localhost:5432"
user = "vidconfAdmin"
password = "vidconfPass"
database = "vidconf"

[recorder]
# The address the monitoring server will listen on.
addr = "0.0.0.0:7071"
# Certs path to configure https
# cert="path/to/cert.pem"
# key="path/to/key.pem"
# Roomid to record session
roomid = "590f9c5c-5462-4fba-be00-5eaf7aaffa6f"
# time in seconds per chopped section
choppedInSeconds = 5
# UserId and UserName used by system to join the room sessions
system_userid = "aeae639f-7a3a-4bcb-ba18-6996cf48e2f2"
system_username = "Public Announcements"

[signal]
# The addr for grpc signalling
addr = "localhost:5551"
