[global]
# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[nats]
url = "nats://127.0.0.1:4222"

[postgres]
addr = "localhost:5432"
user = "vidconfAdmin"
password = "vidconfPass"
database = "vidconf"
roomMgmtSchema = "room-mgmt"
roomRecordSchema = "room-recorder"

[minio]
endpoint = "localhost:9000"
useSSL = false
username = "minioadmin"
password = "minioadmin"
bucketName = "vidconf"

[signal]
# The addr for grpc signalling
addr = "localhost:5551"

[recorder]
# The address the monitoring server will listen on.
addr = "0.0.0.0:7081"
# Roomid to record session
roomid = "bddc3037-be36-446e-a18b-f537307deecd"
# time in seconds per chopped section
choppedInSeconds = 500000
# UserId and UserName used by system to join the room sessions
# Must be identical across "app-room.toml", "app-room-mgmt.toml", "app-room-sentry.toml", "app-room-recorder.toml" & "app-room-playback.toml"
systemUserId = "aeae639f-7a3a-4bcb-ba18-6996cf48e2f2-1"
systemUsername = "Public Announcements"
