[log]
level = "info"
# level = "debug"

[redis]
addrs = [":6379"]
password = ""
db = 0

[recorder]
# The address the monitoring server will listen on.
address = "0.0.0.0:7071"
# Certs path to configure https
# cert="path/to/cert.pem"
# key="path/to/key.pem"
# Roomid to record session
roomid = "73979b1d-0b55-4ae1-adc7-087d550bb9d5"
# time in seconds to per chopped section
choppedInSeconds = 1800
# UserId and UserName used by system to join the room sessions
system_userid = "aeae639f-7a3a-4bcb-ba18-6996cf48e2f2"
system_username = "Public Announcements"

[signal]
# The addr for grpc signalling
addr = "localhost:5551"
