[log]
level = "info"
# level = "debug"

[postgres]
addr = "localhost:5432"
user = "vidconfAdmin"
password = "vidconfPass"
database = "vidconf"
roomMgmtSchema = "room-mgmt"
roomRecordSchema = "room-recorder"

[minio]
endpoint = "play.min.io"
useSSL = true
username = "Q3AM3UQ867SPQQA43P2F"
password = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
# sample attachment filepath in database:
# "vidconf/2202-01-11/aeae639f-7a3a-4bcb-ba18-6996cf48e2f2/attachments/xxxxx.dat"
bucketName = "vidconf"
folderName = "/22020131/aeae639f-7a3a-4bcb-ba18-6996cf48e2f2/"
attachmentFolderName = "/attachment/"
videoFolderName = "/video/"
audioFolderName = "/audio/"

[recorder]
# The address the monitoring server will listen on.
addr = "0.0.0.0:7080"
# Roomid to record session
roomid = "590f9c5c-5462-4fba-be00-5eaf7aaffa6f"
# time in seconds per chopped section
choppedInSeconds = 5
# UserId and UserName used by system to join the room sessions
system_userid = "aeae639f-7a3a-4bcb-ba18-6996cf48e2f2"
system_username = "Public Announcements"

[signal]
# The addr for grpc signalling
addr = "localhost:5551"
