[global]
# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[nats]
url = "nats://nats:4222"

[redis]
addrs = ["redis:6379"]
password = ""
db = 0

[postgres]
addr = "postgres:5432"
user = "vidconfAdmin"
password = "vidconfPass"
database = "vidconf"
roomMgmtSchema = "room-mgmt"
roomRecordSchema = "room-recorder"

[minio]
endpoint = "play.min.io"
useSSL = true
username = "Q3AM3UQ867SPQQA43P2F"
password = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
bucketName = "vidconf"

[roommgmt]
reserved_usernames = ["Public Announcements", "President", "Boss"]
# system_userid used by system to join the room sessions
# Must be identical across "app-room.toml", "app-room-mgmt.toml", "app-room-sentry.toml", "app-room-recorder.toml" & "app-room-playback.toml"
system_userid = "aeae639f-7a3a-4bcb-ba18-6996cf48e2f2"
# playbackIdPrefix used for playback, no recording is performed, up to 8 hexadecimal characters
# Must be identical across "app-room.toml", "app-room-mgmt.toml"
playbackIdPrefix = "bac00cab"
