[log]
level = "info"
# level = "debug"

[stunserver]
urls = ["stun:vidconf:3478", "stun:stunserver:3478", "stun:stun.stunprotocol.org:3478", "stun:stun.l.google.com:19302"]

[nats]
url = "nats://nats:4222"

[postgres]
addr = "vidconf:5432"
user = "vidconfAdmin"
password = "vidconfPass"
database = "vidconf"
roomMgmtSchema = "room-mgmt"
roomRecordSchema = "room-recorder"

[minio]
endpoint = "vidconf:9000"
useSSL = false
username = "minioadmin"
password = "minioadmin"
bucketName = "vidconf"

[signal]
# The addr for grpc signalling
addr = "signal:5551"

[roommgmt]
# systemUserIdPrefix and systemUsername used by system to join the room sessions
# Must be identical across "app-room.toml", "app-room-mgmt.toml", "app-room-sentry.toml", "app-room-recorder.toml" & "app-room-playback.toml"
systemUserIdPrefix = "aeae639f-7a3a-4bcb-ba18-6996cf48e2f2"
systemUsername = "Public Announcements"
# playbackIdPrefix used for playback, no recording is performed, up to 8 hexadecimal characters
# Must be identical across "app-room.toml", "app-room-mgmt.toml", "app-room-recorder.toml", "app-room-playback.toml"
playbackIdPrefix = "bac00cab"

[recorder]
# The address the monitoring server will listen on.
addr = "0.0.0.0:7081"
# time in seconds per chopped section
choppedInSeconds = 5000
