[global]
# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[nats]
url = "nats://127.0.0.1:4222"

[redis]
addrs = [":6379"]
password = ""
db = 0

[roommgmt]
# UserId and UserName used by system to join the room sessions
system_userid = "aeae639f-7a3a-4bcb-ba18-6996cf48e2f2"
